package org.archboy.clobaframe.webresource;

import org.archboy.clobaframe.io.ResourceInfo;

/**
 * The web resource object.
 * <p>
 *     Usually web resource means the java-script/css/image files.
 * </p>
 *
 * @author yang
 *
 */
public interface WebResourceInfo extends ResourceInfo{

	/**
	 * The resource name.
	 * such as 'common.css', 'index.js'.
	 * 
	 * @return
	 */
	String getName();

	/**
	 * Content hash, use MD5/SHA256 algorithm.
	 *
	 * @return
	 */
	String getHash();
	
	/**
	 * Get the alias name of web resource.
	 * <p>
	 *     It's different from the resource name, the "unique name" is used to
	 *     locate web resource by the user's browser.
	 *     and the internally program code should locate web resource by
	 *     "resource name".
	 * </p>
	 * <p>
	 *     The unique name ware generated by implements, normally it's the MD5/SHA256
	 *     String of the resource name and the content data.
	 *     It's would not change after resource repository loaded.
	 * </p>
	 *
	 * @return
	 */
	String getUniqueName();
}
