/*
 * Copyright 2011 Spark Young (sparkyoungs@gmail.com). All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.archboy.clobaframe.webresource;

import org.archboy.clobaframe.io.ResourceInfo;

/**
 * The web resource object.
 * <p>
 *     Usually web resource means the java-script/css/image files.
 * </p>
 *
 * @author young
 *
 */
public interface WebResourceInfo extends ResourceInfo{

	/**
	 * The resource name.
	 * such as 'common.css', 'index.js'.
	 * 
	 * @return
	 */
	String getName();

	/**
	 * Content hash, use MD5/SHA256 algorithm.
	 *
	 * @return
	 */
	String getHash();
	
	/**
	 * Get the alias name of web resource.
	 * <p>
	 *     It's different from the resource name, the "unique name" is used to
	 *     locate web resource by the user's browser.
	 *     and the internally program code should locate web resource by
	 *     "resource name".
	 * </p>
	 * <p>
	 *     The unique name ware generated by implements, normally it's the MD5/SHA256
	 *     String of the resource name and the content data.
	 * </p>
	 *
	 * @return
	 */
	String getUniqueName();
}
